def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.name   = 'libdvdomatic'
    obj.export_includes = ['.']
    obj.uselib = 'GLIB AVFORMAT AVFILTER SWSCALE SWRESAMPLE SNDFILE BOOST_FILESYSTEM GTKMM'
    obj.lib    = 'tiff'
    obj.source = 'film.cc film_writer.cc format.cc progress.cc decoder.cc film_viewer.cc dcp_name.cc film_editor.cc'
    obj.target = 'dvdomatic'
