#
#    Copyright (C) 2012-2015 Carl Hetherington <cth@carlh.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

import os
import i18n

sources = """
          analyse_audio_job.cc
          audio_analysis.cc
          audio_buffers.cc
          audio_content.cc
          audio_decoder.cc
          audio_mapping.cc
          audio_stream.cc
          cinema.cc
          colour_conversion.cc
          config.cc
          content.cc
          content_factory.cc
          cross.cc
          dcp_content_type.cc
          dcp_video_frame.cc
          decoder.cc
          dolby_cp750.cc
          encoder.cc
          examine_content_job.cc
          exceptions.cc
          file_group.cc
          filter_graph.cc
          ffmpeg.cc
          ffmpeg_content.cc
          ffmpeg_decoder.cc
          ffmpeg_examiner.cc
          film.cc
          filter.cc
          frame_rate_change.cc
          internet.cc
          image.cc
          image_content.cc
          image_decoder.cc
          image_examiner.cc
          image_proxy.cc
          isdcf_metadata.cc
          job.cc
          job_manager.cc
          kdm.cc
          json_server.cc
          log.cc
          md5_digester.cc
          piece.cc
          player.cc
          player_video_frame.cc
          playlist.cc
          quickmail.cc
          ratio.cc
          resampler.cc
          safe_stringstream.cc
          scp_dcp_job.cc
          scaler.cc
          send_kdm_email_job.cc
          server.cc
          server_finder.cc
          sndfile_content.cc
          sndfile_decoder.cc
          sound_processor.cc
          subtitle.cc
          subtitle_content.cc
          subtitle_decoder.cc
          timer.cc
          transcode_job.cc
          transcoder.cc
          types.cc
          ui_signaller.cc
          update.cc
          util.cc
          video_content.cc
          video_content_scale.cc
          video_decoder.cc
          writer.cc
          """

def build(bld):
    if bld.env.STATIC_DCPOMATIC:
        obj = bld(features = 'cxx cxxstlib')
    else:
        obj = bld(features = 'cxx cxxshlib')

    obj.name = 'libdcpomatic'
    obj.export_includes = ['..']
    obj.uselib = """
                 AVCODEC AVUTIL AVFORMAT AVFILTER SWSCALE SWRESAMPLE 
                 BOOST_FILESYSTEM BOOST_THREAD BOOST_DATETIME BOOST_SIGNALS2
                 SNDFILE OPENJPEG POSTPROC TIFF MAGICK SSH DCP CXML GLIB LZMA XMLPP
                 CURL ZIP XMLSEC
                 """

    if bld.env.TARGET_OSX:
        obj.framework = ['IOKit', 'Foundation']

    obj.source = sources + ' version.cc'

    if bld.env.TARGET_WINDOWS:
        obj.uselib += ' WINSOCK2 BFD DBGHELP IBERTY SHLWAPI MSWSOCK BOOST_LOCALE'
    if bld.env.STATIC_DCPOMATIC:
        obj.uselib += ' XMLPP'

    obj.target = 'dcpomatic'

    i18n.po_to_mo(os.path.join('src', 'lib'), 'libdcpomatic', bld)

def pot(bld):
    i18n.pot(os.path.join('src', 'lib'), sources, 'libdcpomatic')

def pot_merge(bld):
    i18n.pot_merge(os.path.join('src', 'lib'), 'libdcpomatic')
