#
#    Copyright (C) 2012-2015 Carl Hetherington <cth@carlh.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

def configure(conf):
    boost_test_suffix=''
    if conf.env.TARGET_WINDOWS:
        boost_test_suffix='-mt'

    conf.check_cxx(fragment = """
                              #define BOOST_TEST_MODULE Config test\n
    			      #include <boost/test/unit_test.hpp>\n
                              int main() {}
                              """, msg = 'Checking for boost unit testing library', lib = 'boost_unit_test_framework%s' % boost_test_suffix, uselib_store = 'BOOST_TEST')

def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.name   = 'unit-tests'
    obj.uselib = 'BOOST_TEST BOOST_THREAD DCP OPENJPEG AVFORMAT AVFILTER AVCODEC AVUTIL SWSCALE POSTPROC CXML'
    obj.use    = 'libdcpomatic'
    obj.source = """
                 4k_test.cc
                 audio_analysis_test.cc
                 audio_delay_test.cc
                 audio_mapping_test.cc
                 audio_merger_test.cc
                 black_fill_test.cc
                 client_server_test.cc
                 colour_conversion_test.cc
                 ffmpeg_audio_test.cc
                 ffmpeg_dcp_test.cc
                 ffmpeg_examiner_test.cc
                 ffmpeg_pts_offset.cc
                 file_group_test.cc
                 film_metadata_test.cc
                 frame_rate_test.cc
                 image_test.cc
                 image_filename_sorter_test.cc
                 isdcf_name_test.cc
                 job_test.cc
                 make_black_test.cc
                 pixel_formats_test.cc
                 play_test.cc
                 ratio_test.cc
                 recover_test.cc
                 resampler_test.cc
                 scaling_test.cc
                 silence_padding_test.cc
                 stream_test.cc
                 test.cc
                 threed_test.cc
                 update_checker_test.cc
                 util_test.cc
                 video_content_scale_test.cc
                 """

    obj.target = 'unit-tests'
    obj.install_path = ''
