def build(bld):
    for t in ['dvdomatic', 'makedcp', 'servomatic', 'test']:
        obj = bld(features = 'cxx cxxprogram')
    	obj.uselib = 'BOOST_THREAD GTKMM BOOST_PROGRAM_OPTIONS'
        obj.use    = 'libdvdomatic'
        obj.source = '%s.cc' % t
        obj.target = t
