def build(bld):
    for t in ['test', 'testg', 'film_editor', 'makedcp']:
        obj = bld(features = 'cxx cxxprogram')
    	obj.uselib = 'BOOST_THREAD GTKMM'
        obj.use    = 'libdvdomatic'
        obj.source = '%s.cc' % t
        obj.target = t
