#!/usr/bin/python

import os
import sys
import subprocess

if len(sys.argv) < 2:
    print 'Syntax: %s <DVD-image>' % sys.argv[0]
    sys.exit(1)

lsdvd = subprocess.check_output(['lsdvd', '-c', sys.argv[1]])
lines = lsdvd.decode('utf-8').split('\n')

N = None

for l in lines:
    w = l.split()
    if len(w) > 5 and w[4] == 'Chapters:':
        N = int(w[5][:-1])

if N == None:
    print 'Could not get chapter count.'
    sys.exit(1)

for i in range(1, N + 1):
    c = 'mplayer dvd:// -chapter %d-%d -dvd-device "%s" -dumpstream -dumpfile %d.vob' % (i, i, sys.argv[1], i)
    print c
    os.system(c)


