#!/usr/bin/python

import os
import sys
import tempfile
from xml.dom.minidom import parse

if len(sys.argv) < 3:
    print 'Syntax: %s <DVD-image> <combined-vob>' % sys.argv[0]
    sys.exit(1)

def get_string(e):
    return " ".join(t.nodeValue for t in e.childNodes if t.nodeType == t.TEXT_NODE)

def s_to_hms(s):
    m = int(s / 60)
    s -= m * 60
    h = int(m / 60)
    m -= h * 60
    return '%d:%d:%f' % (h, m, s)

xml = tempfile.NamedTemporaryFile(delete = True)
os.system('lsdvd -Ox -c %s > %s' % (sys.argv[1], xml.name))

mpgsplit = ''

now = 0
dom = parse(xml.name)
for t in dom.getElementsByTagName('track'):
    for c in t.getElementsByTagName('chapter'):
        index = int(get_string(c.getElementsByTagName('ix')[0]))
        length = float(get_string(c.getElementsByTagName('length')[0]))
        print 'ffmpeg -i %s -vcodec copy -acodec copy -ss %s -t %s %d.mpg' % (sys.argv[2], s_to_hms(now + 1), s_to_hms(length), index)
        now += length
