def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.name   = 'libdvdomatic'
    obj.export_includes = ['.']
    obj.uselib = 'AVCODEC AVUTIL AVFORMAT AVFILTER SWSCALE SWRESAMPLE SNDFILE BOOST_FILESYSTEM BOOST_THREAD OPENJPEG POSTPROC TIFF SIGC++'
    if bld.env.DEBUG_HASH:
        obj.uselib += ' MHASH'
    obj.source = """
		 ab_transcode_job.cc
		 ab_transcoder.cc
		 config.cc
		 content_type.cc
		 copy_from_dvd_job.cc
		 dcp_video_frame.cc
		 decoder.cc
                 decoder_factory.cc
		 encoder.cc
		 examine_content_job.cc
                 ffmpeg_decoder.cc
    	         film.cc
		 film_state.cc
		 filter.cc
		 format.cc
                 image.cc
		 j2k_wav_encoder.cc
		 job.cc
		 job_manager.cc
		 log.cc
		 lut.cc
		 make_dcp_job.cc
		 make_mxf_job.cc
		 opendcp_job.cc
		 scaler.cc
		 server.cc
		 thumbs_job.cc
                 tiff_decoder.cc
	         tiff_encoder.cc
                 timer.cc
		 transcode_job.cc
		 transcoder.cc
		 util.cc
		 """
    obj.target = 'dvdomatic'
