def build(bld):
    for t in ['makedcp', 'servomatic', 'servomatictest']:
        obj = bld(features = 'cxx cxxprogram')
    	obj.uselib = 'BOOST_THREAD BOOST_PROGRAM_OPTIONS'
	obj.includes = ['..']
        obj.use    = ['libdvdomatic']
        obj.source = '%s.cc' % t
        obj.target = t

    if not bld.env.DISABLE_GUI:
        for t in ['dvdomatic', 'playomatic']:
            obj = bld(features = 'cxx cxxprogram')
            obj.uselib = 'BOOST_THREAD GTKMM BOOST_PROGRAM_OPTIONS'
            obj.includes = ['..']
            obj.use    = ['libdvdomatic', 'libdvdomatic-gtk']
            obj.source = '%s.cc' % t
            obj.target = t
