#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:$LD_LIBRARY_PATH:build/src
export DYLD_LIBRARY_PATH=build/src/lib:build/src/asdcplib/src:/carl/Environment/64/lib:$DYLD_LIBRARY_PATH
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic_kdm "$@"
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" --leak-check=full --show-reachable=yes build/src/tools/dcpomatic_kdm "$@"
else
    build/src/tools/dcpomatic_kdm "$@"
fi
