#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:$LD_LIBRARY_PATH:build/src
if [ "$1" == "--debug" ]; then
    gdb --args build/src/tools/makedcp $2
elif [ "$1" == "--valgrind" ]; then
    valgrind --tool="memcheck" --leak-check=full --show-reachable=yes build/src/tools/makedcp $2
else
    build/src/tools/makedcp $*
fi
