def build(bld):
    obj = bld(features='subst')
    obj.source = 'dcpomatic.desktop.in'
    obj.target = 'dcpomatic.desktop'
    obj.INSTALL_PREFIX = bld.env.INSTALL_PREFIX
    obj.VERSION = bld.env.VERSION

    obj = bld(features='subst')
    obj.source = 'dcpomatic_batch.desktop.in'
    obj.target = 'dcpomatic_batch.desktop'
    obj.INSTALL_PREFIX = bld.env.INSTALL_PREFIX
    obj.VERSION = bld.env.VERSION

    obj = bld(features='subst')
    obj.source = 'dcpomatic_server.desktop.in'
    obj.target = 'dcpomatic_server.desktop'
    obj.INSTALL_PREFIX = bld.env.INSTALL_PREFIX
    obj.VERSION = bld.env.VERSION

    bld.install_files('${PREFIX}/share/applications', ['dcpomatic.desktop', 'dcpomatic_batch.desktop', 'dcpomatic_server.desktop'])
