#
#    Copyright (C) 2012-2015 Carl Hetherington <cth@carlh.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

import os
import glob
from waflib import Logs
import i18n

def configure(conf):
    if conf.env.TARGET_WINDOWS:
        conf.env.append_value('CXXFLAGS', ['-mconsole'])
        conf.env.append_value('LINKFLAGS', ['-mconsole'])

def build(bld):
    for t in ['dcpomatic_cli', 'dcpomatic_server_cli', 'server_test', 'dcpomatic_kdm', 'dcpomatic_create']:
        obj = bld(features = 'cxx cxxprogram')
        obj.uselib = 'BOOST_THREAD BOOST_DATETIME OPENJPEG DCP XMLSEC CXML XMLPP AVFORMAT AVFILTER AVCODEC AVUTIL SWSCALE POSTPROC CURL BOOST_FILESYSTEM SSH'
        obj.includes = ['..']
        obj.use    = ['libdcpomatic']
        obj.source = '%s.cc' % t
        obj.target = t
        if t == 'server_test':
            obj.install_path = None

    if not bld.env.DISABLE_GUI:
        for t in ['dcpomatic', 'dcpomatic_batch', 'dcpomatic_server']:
            obj = bld(features = 'cxx cxxprogram')
            obj.uselib = 'BOOST_THREAD BOOST_DATETIME OPENJPEG DCP XMLSEC CXML XMLPP AVFORMAT AVFILTER AVCODEC AVUTIL SWSCALE POSTPROC CXML WXWIDGETS CURL BOOST_FILESYSTEM SSH'
            if bld.env.DCPOMATIC_LINUX:
                obj.uselib += ' GTK'
            obj.includes = ['..']
            obj.use    = ['libdcpomatic', 'libdcpomatic-wx']
            obj.source = '%s.cc' % t
            if bld.env.TARGET_WINDOWS:
                obj.source += ' ../../platform/windows/dcpomatic.rc'
            obj.target = t

        i18n.po_to_mo(os.path.join('src', 'tools'), 'dcpomatic', bld)

def pot(bld):
    i18n.pot(os.path.join('src', 'tools'), 'dcpomatic.cc dcpomatic_batch.cc', 'dcpomatic')

def pot_merge(bld):
    i18n.pot_merge(os.path.join('src', 'tools'), 'dcpomatic')
